### ISSUE TITLE
 Error with declaration op setLogger()

### ISSUE THREAD

**Issue by BBrunekreeft** [thirtybees/postnl-api-php#51]
PHPCS produces an error when using `psr/log 3`: 

`PHP Fatal error:  Declaration of Firstred\PostNL\HttpClient\BaseHttpClient::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /home/runner/work/intranet/intranet/vendor/firstred/postnl-api-php/src/HttpClient/CurlClient.php on line 185`

There are no problems with psr/log v1 and v2.

**Comment by firstred** [comment]
Hi @BBrunekreeft 

Thanks for reporting this issue! I think that, for a quick solution, the `BaseHttpClient.php` file will have to be split into two separate versions. One that supports PHP 8.0 return types (required for `psr/log` 2 and 3) and one to keep PHP 5.6 support.
Including the 8.0 file when `psr/log` `>=3.0` is used and PHP `>=7.4` should keep breaking part of this change to a minimum.

If this method works, I'll release a new version as soon as possible.

**Comment by firstred** [comment]
Nope, that requires too many breaking changes. I am going to remove `psr/log ^3.0` from the dependencies. It simply is not compatible, so it shouldn't have been in `composer.json` at all. Since the majority of logging libraries support 1 & 2 & 3 simultaneously I don't think it causes too much trouble, but does solve this issue.

Please feel free to open a new issue if that doesn't work for you. Return types have been long overdue, I just haven't found the time yet to update this library.
