### ISSUE TITLE
Incomplete addresses in result of  PostNL::getShippingStatusByBarcode

### ISSUE THREAD

**Issue by BBrunekreeft** [thirtybees/postnl-api-php#53]
When using  `PostNL::getShippingStatusByBarcode($label)`, the returned addresses are incomplete.
The reason for this, is that some properties are named differently.

The addresses are mapped to `Firstred\PostNL\Entity\Address()` .
Maybe there should be another Address entity for use with CurrentStatusResponse (e.g. StatusResponseAddress)

The differences are as follows:
**Firstred\PostNL\Entity\Address()** | **Address in CurrentStatusResponse** 
-|-
Area | District
Buildingname|Building
Countrycode|CountryCode
Department|DepartmentName
Doorcode|_missing_
HouseNr|HouseNumber
HouseNrExt|HouseNumberSuffix
Name|LastName

**Comment by firstred** [comment]
Thanks for this info! Adding a new Address entity for the current status response might indeed be the best solution.

Is the doorcode truly missing from the address in the current status response? According to the documentation it is possible that a doorcode is returned: https://developer.postnl.nl/browse-apis/send-and-track/shippingstatus-webservice/documentation/

Returning an entirely new entity is a breaking change, but since this is the first report I received concerning the address in the current status response, it should not be a problem.

**Comment by BBrunekreeft** [comment]
I've checked the resonse once again, and the doorcode is not returned in my response.

**Comment by firstred** [comment]
A new `Firstred\PostNL\Entity\StatusAddress` object has been introduced. Will update the libary soon.
