### ISSUE TITLE
Exception thrown when Guzzle can't establish a connection

### ISSUE THREAD

**Issue by daniel-memo-ict** [thirtybees/postnl-api-php#55]
When Guzzle cannot establish a connection, for example when developing locally and you disconnect your internet, the GuzzleClient throws a TypeError on [line 115](https://github.com/firstred/postnl-api-php/blob/e9db072c7b2d7bed937671ea30e42bf3f062ca44/src/HttpClient/GuzzleClient.php#L115) because it expects a ConnectException and not a RequestException.

Would suggest using the GuzzleException interface as typehint, as that is being implemented by all Guzzle exceptions, so it should not throw an error.

**Comment by firstred** [comment]
Thanks for opening this issue!

I think this may be caused by the differences between Guzzle 6 & 7, but will have to look into that.

It used to be a generic `RequestException` with Guzzle 6 so that you could determine, based on the cause of the problem, whether to retry or not. Any instance of `ConnectException` or HTTP status >= 500 would be a reason to reconnect.

It looks like Guzzle 7 passes more specific exceptions based on the cause, but I'll have to reread Guzzle's manual to see whether that's the case.

**Comment by firstred** [comment]
There's unfortunately no documentation on what should be passed to the decider function within the retry handler. The code comments in version 7's retry handler describe the decider as a:
```
Function that accepts the number of retries, a request, [response], and [exception] and returns true if the request is to be retried.
```

A `ConnectException` since version 7 no longer extends a `RequestException` so that's the immediate problem.

I can verify that the exceptions passed with version 6 and 7 of the Guzzle client indeed all implement `GuzzleException` so I'll go with your suggestion. Should be an easy fix. Thanks for sharing!

**Comment by firstred** [comment]
I just pushed https://github.com/firstred/postnl-api-php/commit/d5dbb272240b54a983eda4e6e6e1d99495edc3cc 
Will update the library soon.
