### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ameenross** [thirtybees/postnl-api-php#74]
Hi,

I'm the [original](https://github.com/DivideBV/Postnl) author of this library before it was forked. The original was licensed GPL-2, now I noticed this library is re-licensed MIT. AFAIK you cannot do this without the original author's (my) permission. Did you look at the [license conditions](https://github.com/DivideBV/Postnl/blob/master/LICENSE) before redistributing?

**Comment by firstred** [comment]
Hi,

First of all, thanks for your request! It's great to see folk out there defending GPL. I have an Android app coming up; without GPL I wouldn't have even thought of releasing it. It's a good way to keep the source code open and redistributions available for everyone.

However, that wasn't the goal for this project, hence the MIT license with fewer restrictions.
I have done my utmost to keep this project restricted to MIT licenses only. As you can see, the forked code in this library, mostly from Guzzle, is MIT licensed as well.

Could you let me know which files/lines of codes are licensed incorrectly? I have had a good look at both repositories (https://github.com/DivideBV/Postnl/ and https://github.com/firstred/postnl-api-php/), but could not find anything myself.
This project is not a fork and the SOAP structure seems to be the only thing these projects have in common, but that is just how you communicate with the API, the design of which is laid out by PostNL. If you think differently, please don't hesisitate to let me know. It is important that this library stays MIT without being overruled by any GPL parts.

**Comment by ameenross** [comment]
I have to say I find your response rather peculiar. Surely you remember how you started the project a couple of years ago, and you shouldn't need to check your source code if you are confident you didn't copy it?

Yes, you have replaced the complex types with a Sabre XML based implementation, but it took me all of 1 minute to conclude that you clearly copied my project or at least parts of it.

I was actually considering re-licensing as MIT and give you a pass, but now that you are denying I'm not so sure anymore.

### A couple of things that are obvious copies.

The readme has a table with the implemented services:
![image](https://user-images.githubusercontent.com/859737/213132463-1814f4a2-58c8-4c0c-ad99-a6fe89a97089.png)
 just like mine:
![image](https://user-images.githubusercontent.com/859737/213132570-00a3c257-d840-4a21-b4ca-180c7b1bce7c.png)

The base class of your entities has a create method practically identical to mine, although you changed the implementation to something that kind of defeats the purpose of bypassing the constructor:

```php
// yours
    /**
     * Create an instance of this class without touching the constructor.
     * [...]
     */
    public static function create(array $properties = [])
    {
        /***/
            $reflectionClass = new ReflectionClass(get_called_class());
            $instance = $reflectionClass->newInstanceWithoutConstructor();
        /***/
    }

// mine
    /**
     * Create a class instance statically without calling the constructor.
     *
     * @return $this
     */
    public static function create()
    {
        $reflection = new ReflectionClass(get_called_class());
        return $reflection->newInstanceWithoutConstructor();
    }
```

General structure of the main file (called Postnl.php on my side, PostNL.php on your side) has striking similarities. In particular the barcode generation functions:

```php
// yours
    /**
     * Generate a single barcode
     * [...]
     */
    public function generateBarcode($type, $range = null, $serie = null, $eps = false)
    {
        if (!in_array($type, ['2S', '3S', 'CC', 'CD', 'CF', 'CP', 'CX'])) {
            throw new InvalidBarcodeException("Barcode type `$type` is invalid");
        }

        if (!$range) {
            if (in_array($type, ['2S', '3S'])) {
                $range = $this->getCustomer()->getCustomerCode();
            } else {
                $range = $this->getCustomer()->getGlobalPackCustomerCode();
            }
        }
        if (!$range) {
            throw new InvalidBarcodeException('Unable to find a valid range');
        }

        if (!$serie) {
            $serie = $this->findBarcodeSerie($type, $range, $eps);
        }
        /***/
    }

    /**
     * Generate a single barcode by country code
     * [...]
     */
    public function generateBarcodeByCountryCode($iso)
    {
        /***/
    }

    /**
     * Find a suitable serie for the barcode
     * [...]
     */
    protected function findBarcodeSerie($type, $range, $eps)
    {
        switch ($type) {
            case '2S':
                $serie = '0000000-9999999';

                break;
            case '3S':
                if ($eps) {
                    switch (strlen($range)) {
                        case 4:
                            $serie = '0000000-9999999';

                            break 2;
                        case 3:
                            $serie = '10000000-20000000';

                            break 2;
                        case 1:
                            $serie = '5210500000-5210600000';

                            break 2;
                        default:
                            throw new InvalidBarcodeException('Invalid range');

                            break;
                    }
                }
                // Regular domestic codes
                $serie = (strlen($range) === 4 ? '987000000-987600000' : '0000000-9999999');

                break;
            default:
                // GlobalPack
                $serie = '0000-9999';

                break;
        }

        return $serie;
    }

//mine
    public function generateBarcode(
        $type,
        $customerCode = null,
        $customerNumber = null,
        $serie = null,
        $eps = false
    ) {
        // Validate $type parameter.
        if (!in_array($type, ['2S', '3S', 'CC', 'CP', 'CD', 'CF', 'CV', 'CL'])) {
            throw new Exceptions\InvalidBarcodeTypeException($type);
        }

        // Default customer code and number.
        if (!$customerCode) {
            // Use the separate Globalpack customer code for those shipments.
            $customerCode = in_array($type, ['2S', '3S']) ? $this->customerCode : $this->globalPackCustomerCode;
        }
        $customerNumber = $customerNumber ?: $this->customerNumber;

        // Default serie.
        if (!$serie) {
            switch ($type) {
                case '2S':
                    $serie = '0000000-9999999';
                    break;
                case '3S':
                    // 3S barcodes are the only ones that may be 15 characters
                    // long.
                    $serie = '000000000-999999999';
                    if ($eps) {
                        // 3S barcodes for EPS parcels need to be 13 characters
                        // long.
                        $serie = '0000000-9999999';
                    }
                    break;
                default:
                    // Globalpack is 4 digits, because the barcode is suffixed
                    // with the ISO country code.
                    $serie = '0000-9999';
            }
        }
        /***/
    }

    /**
     * Generate the right type of barcode for the given country code.
     * [...]
     */
    public function generateBarcodeByDestination(
        $countryCode,
        $customerCode = null,
        $customerNumber = null,
        $serie = null
    ) {
        $eps = false;

        // If this country code has an explicit barcode type mapping, use it.
        if (in_array($countryCode, array_keys($this->countryCodeMapping))) {
            $type = $this->countryCodeMapping[$countryCode];
            $eps = $countryCode != 'NL';
        } else {
            // Otherwise use GlobalPack.
            $type = $this->globalPackBarcodeType;
        }
        return $this->generateBarcode($type, $customerCode, $customerNumber, $serie, $eps);
    }
```

I didn't do an exhaustive search, but it's obvious that you copied code from elsewhere. You even copied Guzzle instead of just requiring it, which is rather surprising as well. I'm curious about your response.

**Comment by firstred** [comment]
> I have to say I find your response rather peculiar. Surely you remember how you started the project a couple of years ago, and you shouldn't need to check your source code if you are confident you didn't copy it?

I don't know what to tell you. As I said before, this project is based on the SOAP structure and the PostNL API, with its own design and developer documentation. It is therefore no coincidence that we end up with the same data transfer objects (or complex types as you'd like to call them, I believe?).

Copying is part of the open source process, that is why we all choose our open source licenses carefully. It becomes problematic when redistributions happen without complying with the original license or breaking copyright laws. You mention that this library has been redistributed without your consent and needs to be places under your license, so all my remarks in this post will be aimed at the fact that you claim to be the legal copyright holder of this project.

> I was actually considering re-licensing as MIT and give you a pass, but now that you are denying I'm not so sure anymore.

That is okay, I do not need your permission. In order for you to license the code it has to be copyrighted first, but I reject all your claims.

> A couple of things that are obvious copies.
> The readme has a table with the implemented services:

A basic markdown table, with standard ASCII checkmarks. I don't know where that comes from, but seriously? The names of the services are all PostNL's and it's too common on this website to be even remotely eligible for copyright. When I asked for code samples I was asking for work that contains your style, your touch, your 'finesse'. Only creative work can be copyrighted.

> The base class of your entities has a create method practically identical to mine, although you changed the implementation to something that kind of defeats the purpose of bypassing the constructor:

You conveniently left out all the parts from my code that are not basic PHP syntax. This is indeed how you instantiate a class without calling the constructor. All too common and a requirement to make Sabre XML work.

> General structure of the main file (called Postnl.php on my side, PostNL.php on your side) 

A facade called PostNL in a PostNL library, with different naming conventions. Even if you were the trademark owner, you wouldn't have had the sole rights to simply mention a brand name.

> General structure of the main file ([..]) has striking similarities. In particular the barcode generation functions:

You only mention the barcode function, so that's the only actual PostNL-related piece of code I can comment on. You did not mention which lines of code are your creative work, so that leaves it up to me to guess which parts have come to be by your creative doing.
This function is clearly based on the barcode service as described in the developer documentation: https://developer.postnl.nl/browse-apis/send-and-track/barcode-webservice/
The exception names are based on the error responses of the API. The parameter names are mostly the same as in the documentation. This only leaves the question of where the `eps` parameter comes from. The developer site mentions parcels EU: https://developer.postnl.nl/browse-apis/send-and-track/products/#destination-EU and the predecessor was called the European Parcel Service, abbreviated by PostNL itself to EPS in their own terms & conditions: https://www.postnl.be/en/Images/eng-pakketten-general-terms-and-conditions-for-the-transport-of-goods_tcm75-226917.pdf and https://docplayer.nl/2602294-Algemene-voorwaarden-postnl-pakketten-belgie-nv-sa.html
The parcels EU documentation describes a few exceptions to `eps` ranges. I can see the same thought process here, but not the same code: leaving out the names provided by PostNL and the number ranges mentioned in the developer documentation there is only one PHP control structure left and that is something that is certainly not copyrightable.

> I didn't do an exhaustive search, but it's obvious that you copied code from elsewhere. You even copied Guzzle instead of just requiring it, which is rather surprising as well. I'm curious about your response.

As I mentioned before, copying is part of the open source process. It has all happened under the corresponding licenses and applicable copyright legislation. There are a few utility classes that had to be modified to make them backwards compatible with older versions of PHP, making it impossible to refer to them in `composer.json`. Luckily the MIT license allowed for such modifications. That is why I keep defending this license model for libraries such as this one.

That is also the reason why I have to draw a clear line here and reject your claims. Next you may require me to rename all files because you claim to be the only person who can make PHP files end with the `.php` extension.

**Comment by ameenross** [comment]
You counter with reductio ad absurdum... I'm not sure that helps your case...

> You did not mention which lines of code are your creative work

Did you even read properly before replying with ridicule? I copied my and your functions with some parts left out for brevity. It's clearly visible that you copied the code to determine a barcode `serie` so the user doesn't have to (just to focus on 1 example). The code is adapted slightly, sure!

> Only creative work can be copyrighted.

How convenient. You copied something verbatim (and changed underscores to dots), but you simply say it wasn't creative in your opinion so it's valid to copy.

> I have done my utmost to keep this project restricted to MIT licenses only.

> It is important that this library stays MIT without being overruled by any GPL parts.

There is your motive, laid out by yourself.

Whatever, I don't care to pursue this further as I have better things to do. I just think you did the open source community a disservice with this and I'll leave it at that. I'll just say one more thing:

> I have had a good look at both repositories but could not find anything myself [...] If you think differently, please don't hesisitate to let me know

Oh how your tone has changed after this initial welcoming of the issue.
