### ISSUE TITLE
LoggerAwareInterface incompatible

### ISSUE THREAD

**Issue by WeTurkstra** [thirtybees/postnl-api-php#76]
Iam trying to use this library in my Symfony 6.2.7 project with php 8.1.

The following error is shown after `composer require`:

Fatal error: Declaration of Firstred\PostNL\HttpClient\BaseHttpClient::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /var/www/vendor/firstred/postnl-api-php/src/HttpClient/BaseHttpClient.php on line 185

I saw an old issue: #51 which removed the requirement for PSR Log 3.0.
But you are still using the interfaces. Therefor when using this library in a project which requires PSR/Log version 3.0 it's going to throw the error shown above. 

Is there anyway for this library to support this?

**Comment by rikvdh** [comment]
I think you either support psr/log or you don't. Currently the return-type is missing for `setLogger` in order to be compatible with psr/log:3. You are now only compatible up to psr/log:2. In order to get compatible with 3 you need to add the return-types but have a version-requirement of at least PHP 8.

In my opinion dropping PHP <= 7 is fair since support is already long gone from the community as a whole. A lot of projects dropped 7 already for a while.

**Comment by WeTurkstra** [comment]
I have to support psr/log:3 because of the framework iam using. For now i forked the repo and updated the return types.

**Comment by rikvdh** [comment]
If you add the correct PHP dependency in composer.json (`"php": "^8.0",`) and make a PR it would get at least my blessing (for what it's worth..)

**Comment by firstred** [comment]
Thanks for the suggestions!

I'll have a look into version 2, which can drop older versions of PHP (anything lower than 8?). There are probably a few more things that can be dropped as well.

**Comment by alexdebeer3005** [comment]
Any update on this?

**Comment by firstred** [comment]
No update, yet.

**Comment by rikvdh** [comment]
@firstred Should someone else work on this and make a PR? I might have the possibility to do so.

**Comment by firstred** [comment]
@rikvdh Thanks for the offer! I'll try to create a list of changes that can be made. I think your feedback will be more important in this phase.


I've had a look at all the things needs to be done for the update.There's unfortunately more work than just updating the dependencies. The old utility classes will have to be replaced as well. This also means figuring out which dependencies can replace the utility classes, and, in particular which versions of those dependencies should be supported.
PHP 8.0+ as a minimum seems like a safe bet. There are plenty of packages out there that have become 8.0+ only, so that should make it easier to select a dependency tree that works for everyone again.
I'll try to create a first alpha version of v2 this week to see if the changes I mentioned will be enough. Thanks everyone for your feedback so far!

**Comment by firstred** [comment]
Oh, and of course some documentation on how to migrate from v1 to v2!

**Comment by firstred** [comment]
Work on version 2.0.x has begun: https://github.com/firstred/postnl-api-php/tree/v2.0.x

It seems that PHP 8.1+ might be the best choice. A lot of libraries have already dropped support for version 8.0.

Some (breaking) fixes that have been postponed forever have also been applied to this new major version. Architectural changes have been made to leverage new language features and remove discrepancies between SOAP and REST calls.

If you are mainly using the `PostNL` class, then the changes should be minimal. I'll make sure that at least these ones get documented. The inner workings of the library have changed a lot, so if you depend on isolated `Service` classes, for example, you might want to test a while before migrating. The v1.x.x branch will likely stay in maintenance mode until PHP 8.x is EOL. I'll provide more info about maintenance when v2.0.0 is released.

**Comment by firstred** [comment]
Version `2.0.0-beta.1` has just been released. There is no documentation for now, but if you follow all deprecation messages from the `v1.4.x` branch, you should be able to easily upgrade. The changes in the `PostNL` main facade are minimal.
Notable changes to keep in mind: no support for SOAP (so no API mode to be set), service classes have been refactored & dependencies have been updated. The latter might make it impossible to install the new version. If you have found an incompatible mix of composer dependencies, please leave a comment.
